module group_bench {
	typedef short parameter ;
	interface init {
		 void init_group_bench();
	};
	interface loop {
		void group_bench(in char MB, in parameter nbBlocks);
	};
	interface end {
		 void end_group_bench();
	}; 
};
