module StockBlocksCr {
	typedef short int;
    interface loop{
         void StockBlocksCr(in int MB_courant,in short InverseQuant_BlkXn_5,in char VOLsimple,in int resync_marker
         						,out short Cr_BuffA,out short Cr_BuffB,out short Cr_BuffC);

    };
}; 


