/*
 * generated by Xtext
 */
package org.ietr.preesm.editor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IDLLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.ietr.preesm.editor.ui.internal.IDLLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.ietr.preesm.editor.ui.internal.IDLLanguageActivator.getInstance().getInjector("org.ietr.preesm.editor.IDLLanguage");
	}
	
}
