module extract_picture {
	typedef short int;
	interface init{
		int Init_SDL(in int edge,in int xpic,in int ypic);
	};
    interface loop{
		void SDL_Display_preesm(in int edge,in char Display_Extract_Image);
    };
    interface end{
    	void CloseSDLDisplay();
    };
}; 

