module init_decode_I_frame {
	typedef short int;
    interface loop{
		void init_decode_I_frame_preesm ( in char VOLsimple, in int pos_i, in char frame_Y_i, in char frame_U_i, in char frame_V_i, in char keyframes_i
									, out char InverseQuant_BlkXn_0, out char InverseQuant_BlkXn_1, out char InverseQuant_BlkXn_2, out char InverseQuant_BlkXn_3
									, out char InverseQuant_BlkXn_4, out char InverseQuant_BlkXn_5, out char adresse, out char display, out char keyframes_o
									, out char pos_o, out char tab_pos_X);
    };
}; 

