/*
* generated by Xtext
*/
package org.ietr.preesm.editor.ui.contentassist;

import org.ietr.preesm.editor.ui.contentassist.AbstractIDLLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IDLLanguageProposalProvider extends AbstractIDLLanguageProposalProvider {

}
