module dataSort {
	typedef long parameter;
	interface init{
		void init_sort();
	};
	interface loop{
		void sortData( in char initIn, in char iterateIn, in char trig,out char data1Out,out char data2Out, out char weights,in parameter size);
	};
	interface end{
		void end_sort();
	};
};
