module Concat_stream_err_pred {
	interface loop{
	void Concat_stream_ErPred_16 ( in any Global
							  , in char  buff_stream_error_2,   in long Taille_stream_error_2
							  , in char  buff_stream_signe_2, 	in long Taille_stream_signe_2
							  , in char  buff_stream_error_4,   in long Taille_stream_error_4
							  , in char  buff_stream_signe_4, 	in long Taille_stream_signe_4
							  , in char  buff_stream_error_8,   in long Taille_stream_error_8
							  , in char  buff_stream_signe_8, 	in long Taille_stream_signe_8
							  , in char  buff_stream_error_16,  in long Taille_stream_error_16
							  , in char  buff_stream_signe_16,	in long Taille_stream_signe_16
							  , out char stream_Error_Pred, 	out long Taille_stream_Error_Pred );
	};
	
};
