module Concate_stream_quad {
	interface loop{
   void Concat_stream_quad_16 (  							 in char buffer_bin1
							   , in long Taille_buffer_bin1, in char buffer_bin2
							   , in long Taille_buffer_bin2, in char buffer_bin3
							   , in long Taille_buffer_bin3, out char stream_quad
							   , out long Taille_flux_quad );
	};
	
};
