module Explode_stream_ErPred {
	interface loop{
	void Explode_stream_ErPred_16 ( in short Stream_Err_Pred
							, out long Coef_Quant
							, 						   out char buff_error_2
							, out long taille_error_2, out char buff_signe_2 
							, out long taille_signe_2, out char buff_error_4
							, out long taille_error_4, out char buff_signe_4
							, out long taille_signe_4, out char buff_error_8
							, out long taille_error_8, out char buff_signe_8
							, out long taille_signe_8, out char buff_error_16
							, out long taille_error_16,out char buff_signe_16
							, out long taille_signe_16 );
	};
	
};
