module Extract_error_symb_16 {
	interface loop{
	//void Extract_Error_Symb_16 ( const LAR *LarParams, const int Ratio
	//						, const unsigned char * RESTRICT im_tail
	//						, const short * RESTRICT imErPr, unsigned char * RESTRICT buffer_error_2_uchar
	//						, int * RESTRICT Taille_error_2_uchar, unsigned char * RESTRICT buffer_signe_2_uchar
	//						, int * RESTRICT Taille_signe_2_uchar, unsigned char * RESTRICT buffer_error_4_uchar
	//						, int * RESTRICT Taille_error_4_uchar, unsigned char * RESTRICT buffer_signe_4_uchar
	//						, int * RESTRICT Taille_signe_4_uchar, unsigned char * RESTRICT buffer_error_8_uchar
	//						, int * RESTRICT Taille_error_8_uchar, unsigned char * RESTRICT buffer_signe_8_uchar
	//						, int * RESTRICT Taille_signe_8_uchar, unsigned char * RESTRICT buffer_error_16_uchar
	//						, int * RESTRICT Taille_error_16_uchar, unsigned char * RESTRICT buffer_signe_16_uchar
	//						, int * RESTRICT Taille_signe_16_uchar )
	void Extract_Error_Symb_16 ( in any Global, in int ratio
							, in char im_tailles_i
							, in short imErPr, 		   		out char buff_error_2
							, out long taille_error_2, out char buff_signe_2 
							, out long taille_signe_2, out char buff_error_4
							, out long taille_error_4, out char buff_signe_4
							, out long taille_signe_4, out char buff_error_8
							, out long taille_error_8, out char buff_signe_8
							, out long taille_signe_8, out char buff_error_16
							, out long taille_error_16,out char buff_signe_16
							, out long taille_signe_16 );
	};
	
};
