module Extract_error_symb{
	typedef long parameter;
	interface loop{
	void Extract_Error_Symb_16 ( in any Global, in parameter ratio
								, in char im_tailles_i, in long im_Error_pred_i, 
														   out char buff_error_2
								, out long taille_error_2, out char buff_signe_2 
								, out long taille_signe_2, out char buff_error_4
								, out long taille_error_4, out char buff_signe_4
								, out long taille_signe_4, out char buff_error_8
								, out long taille_error_8, out char buff_signe_8
								, out long taille_signe_8, out char buff_error_16
								, out long taille_error_16,out char buff_signe_16
								, out long taille_signe_16 );
	};
	
};
