module Rebuild_Error_Symb {
	typedef long parameter;
	interface loop{
	void Rebuild_Error_Symb_16 ( in any Global , in parameter ratio , in char im_tailles_i
							,  in char buff_stream_error_2
							,  in char buff_stream_signe_2
							,  in char buff_stream_error_4
							,  in char buff_stream_signe_4
							,  in char buff_stream_error_8
							,  in char buff_stream_signe_8
							,  in char buff_stream_error_16
							,  in char buff_stream_signe_16, out short stream_ErPred );
	};
	
};
