<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codegen" nsURI="http://codegen/1.0" nsPrefix="codegen">
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//CodeElt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElts" upperBound="-1"
        eType="#//CodeElt" changeable="false" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Variable" changeable="false" eOpposite="#//Variable/users"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//Variable" containment="true" eOpposite="#//Variable/creator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeElt" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true" eSuperTypes="#//CodeElt">
    <eOperations name="addParameter">
      <eParameters name="variable" eType="#//Variable"/>
      <eParameters name="direction" eType="#//PortDirection"/>
    </eOperations>
    <eOperations name="removeParameter">
      <eParameters name="variable" eType="#//Variable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Variable" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Call"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterDirections" unique="false"
        upperBound="-1" eType="#//PortDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Commentable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creator" eType="#//Block"
        eOpposite="#//Block/definitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" lowerBound="1" upperBound="-1"
        eType="#//Block" changeable="false" eOpposite="#//Block/declarations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrens" upperBound="-1"
        eType="#//SubBuffer" eOpposite="#//SubBuffer/container"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergedRange" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="#//range"/>
        <eTypeArguments eClassifier="#//Buffer"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubBuffer" eSuperTypes="#//Buffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Buffer" eOpposite="#//Buffer/childrens"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actorName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//Call">
    <eOperations name="getCoreContainer" lowerBound="1" eType="#//CoreBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" lowerBound="1"
        eType="#//Delimiter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Buffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendStart" eType="#//Communication"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendEnd" eType="#//Communication"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveStart" eType="#//Communication"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveEnd" eType="#//Communication"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//CommunicationNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveRelease" eType="#//Communication"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendReserve" eType="#//Communication"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="SEND"/>
    <eLiterals name="RECEIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Delimiter">
    <eLiterals name="START"/>
    <eLiterals name="END" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopBlock" lowerBound="1"
        eType="#//LoopBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initBlock" lowerBound="1"
        eType="#//CallBlock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coreType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loopBlock" lowerBound="1"
        eType="#//LoopBlock"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initBlock" lowerBound="1"
        eType="#//CallBlock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorCall" eSuperTypes="#//Call"/>
  <eClassifiers xsi:type="ecore:EClass" name="CallBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialCall" eSuperTypes="#//Call">
    <eOperations name="isFork" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isJoin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isBroadcast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isRoundBuffer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="addInputBuffer">
      <eParameters name="buffer" eType="#//Buffer"/>
    </eOperations>
    <eOperations name="addOutputBuffer">
      <eParameters name="buffer" eType="#//Buffer"/>
    </eOperations>
    <eOperations name="removeInputBuffer">
      <eParameters name="buffer" eType="#//Buffer"/>
    </eOperations>
    <eOperations name="removeOutputBuffer">
      <eParameters name="buffer" eType="#//Buffer"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SpecialType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputBuffers" lowerBound="1"
        upperBound="-1" eType="#//Buffer" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputBuffers" lowerBound="1"
        upperBound="-1" eType="#//Buffer" changeable="false" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SpecialType">
    <eLiterals name="FORK"/>
    <eLiterals name="JOIN" value="1"/>
    <eLiterals name="BROADCAST" value="2"/>
    <eLiterals name="ROUND_BUFFER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FifoCall" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//FifoOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fifoHead" eType="#//FifoCall"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fifoTail" eType="#//FifoCall"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headBuffer" eType="#//Buffer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyBuffer" eType="#//Buffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FifoOperation">
    <eLiterals name="PUSH"/>
    <eLiterals name="POP" value="1"/>
    <eLiterals name="INIT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commentable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semaphore" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="SharedMemoryCommunication" eSuperTypes="#//Communication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semaphore" lowerBound="1"
        eType="#//Semaphore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortDirection">
    <eLiterals name="INPUT"/>
    <eLiterals name="OUTPUT" value="1"/>
    <eLiterals name="NONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantString" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullBuffer" eSuperTypes="#//SubBuffer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="range" instanceClassName="org.ietr.preesm.experiment.memory.Range"/>
</ecore:EPackage>
