<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="codegen" nsURI="http://codegen/1.0" nsPrefix="codegen">
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//CodeElt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeElts" upperBound="-1"
        eType="#//CodeElt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="#//Variable" eOpposite="#//Variable/users"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeElt" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true" eSuperTypes="#//CodeElt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creator" lowerBound="1"
        eType="#//Block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" lowerBound="1" upperBound="-1"
        eType="#//Block" eOpposite="#//Block/declarations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubBuffer" eSuperTypes="#//Buffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Buffer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Call"/>
  <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1"
        eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" lowerBound="1"
        eType="#//Delimiter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="SEND"/>
    <eLiterals name="RECEIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Delimiter">
    <eLiterals name="START"/>
    <eLiterals name="END" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopBlock" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorCall" eSuperTypes="#//Call"/>
</ecore:EPackage>
