/*
 * generated by Xtext
 */
package org.ietr.preesm.editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IDLLanguageUiModule extends org.ietr.preesm.editor.ui.AbstractIDLLanguageUiModule {
	public IDLLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
