/*
 * generated by Xtext
 */
package org.ietr.preesm.editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IDLLanguageRuntimeModule extends org.ietr.preesm.editor.AbstractIDLLanguageRuntimeModule {

}
