module StockBlocksLum {
	typedef short int;
    interface loop{
         void StockBlocksLum(in char MB_courant,in int resync_marker,in short InverseQuant_BlkXn_1,in short InverseQuant_BlkXn_2,in short InverseQuant_BlkXn_3
         						,in char VOLsimple,out short BuffA,out short BuffB,out short BuffC,out short BuffD,out short BuffE);
    };
}; 

