
module displayRGB {
	typedef long parameter ;
	interface init {
		void displayRGBInit (in parameter index, in parameter height , in parameter width);
	} ;
	interface loop {
		void displayRGB (in parameter index , in parameter height , in parameter width, in char rgb);
	} ;
} ;