module displayPic {
	typedef long parameter ;
	interface init {
		void Display_YUV_init (in parameter index, in parameter xsize, in parameter ysize);
	};
	interface loop {
		void Display_YUV (in parameter index, in char Y, in char U, in char V);
	};
};