/*
* generated by Xtext
*/
package org.ietr.preesm.editor.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class IDLLanguageTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
