/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is false */

void clip(int * I, int * sign , int *O ) ;
void RightShift(int * x , int * Out ) ;


void RightShift(int * x , int * Out ) 
{ int i ;

  {
  i = 0;
  while (i < 64) {
    Out[i] = x[i] >> 13;
    i ++;
  }
}
}

void clip(int * I, int * sign , int *O ) 
{ int min ;
  int y [64] ;
  int i = 0;
  int _if_5 ;
  RightShift(I, y);

  {
  if (*sign) {
    _if_5 = -255;
  } else {
    _if_5 = 0;
  }
  min = _if_5;
  while (i < 64) {
	  if (y[i] > 255) {
		O[i] = 255;
	  } else {
		if (y[i] < min) {
		  O[i] = min;
		} else {
		  O[i] = y[i];
		}
	  }
	  i ++ ;
  }
}
}
