name: Build & Test - Master weekly
on:
  schedule:
    - cron:  '0 6 * * MON'
    
jobs:
  build:
    name: Build & Test - Master weekly
    strategy:
      matrix:
        # os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        # java-version: [11, 12, 13, 14]
        os: [ubuntu-20.04]
        java-version: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build & Test
        shell: bash
        run: releng/build_and_test.sh --ci        
      - name: Analyze with SONAR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -e -c -Dtycho.mode=maven jacoco:report -Djacoco.dataFile=../../target/jacoco.exec -Dsonar.projectKey=preesm_preesm -Dsonar.token=$SONAR_TOKEN sonar:sonar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: preesm-products
          path: releng/org.preesm.product/target/org.preesm.product-*.zip
      - name: Archive Linux product
        uses: actions/upload-artifact@v3
        with:
          name: Linux-products
          path: releng/org.preesm.product/target/products/preesm-*-linux.gtk.x86_64.zip
      - name: Archive macOS aarch64 product
        uses: actions/upload-artifact@v3
        with:
          name: mac-aarch64-products
          path: releng/org.preesm.product/target/products/preesm-*-macosx.cocoa.aarch64.zip
      - name: Archive macOS x86_64 product
        uses: actions/upload-artifact@v3
        with:
          name: mac-x86-products
          path: releng/org.preesm.product/target/products/preesm-*-macosx.cocoa.x86_64.zip
      - name: Archive Windows product
        uses: actions/upload-artifact@v3
        with:
          name: windows-products
          path: releng/org.preesm.product/target/products/preesm-*-win32.win32.x86_64.zip
